import {assets} from '../../assets';
export const doctordetails = [
  {
    id: 1,
    name: 'Dr.Khadim Khan',
    department: 'Dentist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.anil,
    rating:'4.9',
    messageTime: '4 mins ago',
    contactType:'messaging-',
    day:'saturday',
    time:'3:10',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 2,
    name: 'Dr. Maryam Ali Khan',
    department: 'Specialist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.nitin,
    rating:'4.9',
    messageTime: '3 mins ago',
    contactType:'video call-',
    day:'saturday',
    time:'6:30',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 3,
    name: 'Dr.Kabir Khan',
    department: 'Cardiologist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.binod,
    rating:'4.1',
    messageTime: '9 mins ago',
    contactType:'aideo call-',
    day:'saturday',
    time:'3:30',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 4,
    name: 'Dr.Christena jammy',
    department: 'Dentist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.mahima,
    rating:'4.2',
    messageTime: '10 mins ago',
    contactType:'video call-',
    day:'tomoroww',
    time:'5:10',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 5,
    name: 'Dr. Ashley Janelle',
    department: 'Anthologist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.alina,
    rating:'4.9',
    messageTime: '6 mins ago',
    contactType:'aideo call-',
    day:'today',
    time:'5:10',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 6,
    name: 'Dr.Mark John',
    department: 'Child Specialist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.binod,
    rating:'4.1',
    messageTime: '9 mins ago',
    contactType:'video call-',
    day:'Friday',
    time:'5:10',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 7,
    name: 'Dr.Christena jammy',
    department: 'Dentist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.mahima,
    rating:'4.2',
    messageTime: '10 mins ago',
    contactType:'messaging-',
    day:'Tuesday',
    time:'3:10',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
  {
    id: 8,
    name: 'Dr. Ashley Janelle',
    department: 'Anthologist',
    hospitalName: 'Available at Aga khan Hospital Gilgit',
    location: 'Gilgit Baltistan',
    images: assets.alina,
    rating:'4.9',
    messageTime: '6 mins ago',
    contactType:'video call-',
    day:'Wednesday',
    time:'4:10',
    messageText:
      'Hey there, this is my test for a post of my social app in React Native.',
  },
];

export const homeButtonName = [
  {
    id: 1,
    name: 'Snuffle',
  },
  {
    id: 2,
    name: 'High Fiver',
  },
  {
    id: 3,
    name: 'Nauseous',
  },
  {
    id: 5,
    name: 'Covid 19',
  },
  {
    id: 6,
    name: 'heart Pain',
  },
  {
    id: 7,
    name: 'Cancer',
  },
  {
    id: 8,
    name: 'Blood Pressure',
  },
];
